apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.service.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: {{ .Values.service.name }}
        image: {{ .Values.registry }}/{{ .Values.projectId }}/{{ .Values.repository }}/{{ .Values.service.name }}:{{ .Values.service.imageTag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.service.port }}
          name: http
        {{- if .Values.config }}
        envFrom:
        - configMapRef:
            name: {{ .Values.service.name }}-config
        {{- end }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
