namespace: hiring-system
serviceAccountName: default
registry: asia-south1-docker.pkg.dev
projectId: wohlig
repository: hiring-system

service:
  name: admin-console
  imageTag: 3b2e92c8725bef39665b653ffa77ea33e7801627
  port: 8080
  replicas: 1

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "100m"

# Ingress configuration
ingress:
  enabled: true
  fqdn: hiring-admin-console.wohlig.com
  tls:
    enabled: false
    secretName: ""
