namespace: hiring-system
serviceAccountName: default
registry: asia-south1-docker.pkg.dev
projectId: wohlig
repository: hiring-system

service:
  name: recruiter-portal
  imageTag: aaea30d3846d0de4c4fe56690aca4d5959c2bc5a
  port: 8080
  replicas: 1

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "100m"

# Ingress configuration
ingress:
  enabled: true
  fqdn: hiring-recruiter-portal.wohlig.com
  tls:
    enabled: false
    secretName: ""
